repos:
  # Single quality check hook that runs everything
  - repo: local
    hooks:
      - id: check-all
        name: Run all quality checks
        entry: python scripts/check_all.py
        language: system
        pass_filenames: false
        always_run: true