services:
  stockbook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stockbook-app
    ports:
      - "8000:8000"
    volumes:
      - ./data/database:/app/data/database
      - ./data/logs:/app/data/logs
      - ./data/backups:/app/data/backups
    environment:
      - STOCKBOOK_DB_PATH=/app/data/database/stockbook.db
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  default:
    name: stockbook-network