name: CI

on:
  push:
    branches: ['**']  # Run on push to any branch
  pull_request:
    branches: ['**']  # Run on any pull request

jobs:
  quality-check:
    name: Run all quality checks
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Adjust based on your test suite size
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for some checks
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install the package in editable mode for import resolution
          pip install -e .
      
      - name: Run all quality checks
        run: python scripts/check_all.py
        env:
          # Ensure the script has access to all tools
          PYTHONPATH: ${{ github.workspace }}
      
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports
          path: |
            htmlcov/
            .coverage
            coverage-layers.json
          retention-days: 7
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            .pytest_cache/
            pytest-report.xml
          retention-days: 7
          if-no-files-found: ignore